server:
  port: 9001
spring:
   application:
      name:  consumer-hystrix
security:
  basic:
    enabled: true #开启认证
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
logging:
  level:
    root: INFO