server:
  port: 7900
spring:
   application:
      name:  provider-user
security:
  basic:
    enabled: true #开启认证
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
logging:
  level:
    root: INFO